### ISSUE TITLE
Remember to remove tick marks from cropped images at some point

### ISSUE THREAD

**Issue by mkeller99** [dipayan412/rdt-scan#12]

**Comment by goldenpaddler** [comment]
Can we keep the the tick marks on the display and removed them from the save file?

**Comment by mkeller99** [comment]
That sounds good to me if straightforward to implement

**Comment by mkeller99** [comment]
Updated to note:

1. Save a version of cropped image without tick marks as discussed
2. Change orange tick mark color to blue.
