### ISSUE TITLE
Master Branch 310b880 reading wrong peak value and result String not displaying Control peak value

### ISSUE THREAD

**Issue by goldenpaddler** [dipayan412/rdt-scan#21]
The master branch 301b880 is reading the wrong value in the peak array.

The peak value should be read from the index [4} which is the baseline corrected value, currently using index [1] which is the uncorrected value

Result string removed the text "Control" for the string and there is no value even when there is a peak. There decimal places are also not formatted in the string. _I am not sure if we were removing the Control line peak value_ 

This may have been a result of the quick fix to keep the application from crashing, but it appears to have caused other errors.
These changes effect the same code as addSampleID and may have resulted in those changes not working as anticipated.
The peak value should be read from the index [4} which is the baseline corrected value, currently using index [1] which is the uncorrected value

Result string removed the text "Control" for the string and there is no value even when there is a peak. There decimal places are also not formatted in the string.

This may have been a result of the quick fix to keep the application from crashing, but it appears to have caused other errors.
These changes effect the same code as addSampleID and may have resulted in those changes not working as anticipated.

**Comment by dipayan412** [comment]
I am proposing this change to resultString in resultActivity 
`
resultString = "" + (peaks.size() > 0 && peaks.get(0) != null ? "Control " + String.format("%.1f",(peaks.get(0)[3])) + ", ": "");
resultString += "" + (peaks.size() > 1 ? "Test " + String.format("%.1f",(peaks.get(1)[3])) : "");
`
