### ISSUE TITLE
Investigate capture of a higher resolution image 

### ISSUE THREAD

**Issue by mkeller99** [dipayan412/rdt-scan#35]
Priority 1
Best (?) choice - grab higher res image, immediately downscale for live image quality checks, and use high res image for further analysis

Alternate choices include:
ASAP after grabbing the good low-res frame, initiate new camera process and grab high res image; run quality checks on this acquired image after the fact as well?
Other??

**Comment by mkeller99** [comment]
Also seek to acquire high res images from cassettes around LOD to do some separate analyses

**Comment by goldenpaddler** [comment]
Create version that saves high resolution image after passing quality check

**Comment by goldenpaddler** [comment]
will remain separate branch jwshires until after Eval #2 by LFA group
